# - name: Ensure Firewall is disabled
#   ansible.builtin.systemd:
#     name: firewalld
#     state: stopped
#     enabled: false
#   failed_when: false

# - name: Disable SELinux
#   ansible.posix.selinux:
#     state: disabled

- name: Enable EPEL Repo (required for certbot)
  ansible.builtin.dnf:
    name: epel-release
    state: latest
  become: true

- name: Add the Kubernetes yum repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: | 
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
  become: true

- name: Install necessary packages
  ansible.builtin.dnf:
    name:
      - git
      - make
      - jq
      - python-setuptools
      - python3-pip
      - kubectl
      - certbot
    update_cache: true
    state: present
  become: true

- name: Install kubernetes python library
  ansible.builtin.pip:
    name:
      - kubernetes
    state: forcereinstall
  become: true
