- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:
  delay: 15

- name: Stop firewall service
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: Install K3s (this may take up to 5 minutes)
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    chdir: "{{ tmp_dir }}"
  when: k8s_install

- name: "Ensure that /home/{{ ansible_user }}/.kube directory exists"
  ansible.builtin.file:
    path: ~/.kube
    state: directory
  delegate_to: localhost

- name: "Copy kubeconfig file from default location to user {{ ansible_user }}'s home directory"
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: true
  become: true

- name: "Replace the kubeconfig cluster kube-api server IP with the public IP address, if the cluster is remote "
  ansible.builtin.replace:
    path: ~/.kube/config
    regexp: '127.0.0.1'
    replace: "{{ k3s_master_node_ip }}"
  delegate_to: localhost
  when: ansible_host != "localhost"
  

- name: Get a list of all nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    validate_certs: false
  delegate_to: localhost
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"