- name: Create Inventory - {{ inventory.name }}
  awx.awx.inventory:
    controller_host: "http://{{ ascender_ip }}:{{ ascender_port }}"
    controller_username: admin
    controller_password: "{{ ascender_password }}"

    name: "{{ inventory.name }}"
    description: "{{ project.description | default('') }}"
    organization: Default