- name: Create Job Template - {{ template.name }}
  awx.awx.job_template:
    controller_host: "http://{{ ascender_ip }}:{{ ascender_port }}"
    controller_username: admin
    controller_password: "{{ ascender_password }}"

    name: "{{ template.name }}"
    job_type: "{{ template.job_type | default('run') }}"
    organization: Default
    inventory: "{{ template.inventory | default('Default Inventory') }}"
    project: "{{ template.project }}"
    playbook: "{{ template.playbook }}"
    state: present
    survey_enabled: "{{ template.survey_enabled | default(omit) }}"
    survey_spec: "{% if template.survey_file is defined %}{{ lookup('file', template.survey_file) }}{% else %}{{ ''| default(omit, true) }}{% endif %}"
    ask_credential_on_launch: "{{ template.ask_credential_on_launch | default(omit) }}"
    diff_mode: "{{ template.diff_mode | default(omit) }}"
