- hosts: localhost
  become: false
  gather_facts: no

  vars_files:
    - default.config.yml

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
    NAMESPACE: "{{ LEDGER_NAMESPACE }}"
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}" #required as the aws cli lives at /usr/local/bin/aws

  roles:
    - common
    # - k3s

  tasks:

    - name: Create Namespace
      kubernetes.core.k8s:
        name: "{{ LEDGER_NAMESPACE }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: "Run ascender_install role for {{ k8s_platform }}"
      ansible.builtin.include_role:
        name: ledger_install
        tasks_from: "ledger_install_{{ k8s_platform }}"

    - ansible.builtin.debug:
        msg: "Ledger install complete."